[mypy]
python_version = 3.13
ignore_missing_imports = True
follow_imports = skip

# Disable strictness
disallow_untyped_defs = False
disallow_untyped_calls = False
disallow_incomplete_defs = False
warn_unused_ignores = False
warn_return_any = False
warn_no_return = False
warn_unreachable = False
no_implicit_optional = False

# Disable all problematic SQLModel / FastAPI errors
disable_error_code = misc, attr-defined, union-attr, arg-type, assignment, return-value, no-any-return, no-untyped-def, unused-ignore, call-arg

implicit_reexport = True

exclude =
    migrations/
    alembic/
    env/
    venv/
    .venv/
